version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
        open-pull-requests-limit: 20
    -   package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "daily"
        open-pull-requests-limit: 20
    -   package-ecosystem: "docker"
        directory: "/"
        schedule:
            interval: "daily"
        open-pull-requests-limit: 20
